### ISSUE TITLE
Cannot run the Example: An unhandled error has occurred

### ISSUE THREAD

**Issue by win32nipuh** [Allegiance-Consulting/blazor-highcharts#22]
I have copied the solution, built and run it: 

```
Loading...
An unhandled error has occurred. Reload 🗙

```

The browser console shows:
```
Failed to load resource: the server responded with a status of 404 ()
pretty-print.js:1 Failed to load resource: the server responded with a status of 404 ()
blazor.webassembly.js:1 Failed to load resource: the server responded with a status of 404 ()
blazor-highcharts.js:1 Failed to load resource: the server responded with a status of 404 ()
styles.css:1 Failed to load resource: the server responded with a status of 404 ()
site.css:1 Failed to load resource: the server responded with a status of 404 ()
pretty-print.js:1 Failed to load resource: the server responded with a status of 404 ()
blazor.webassembly.js:1 Failed to load resource: the server responded with a status of 404 ()
bootstrap.min.css:1 Failed to load resource: the server responded with a status of 404 ()
site.css:1 Failed to load resource: the server responded with a status of 404 ()
styles.css:1 Failed to load resource: the server responded with a status of 404 ()

```

How to fix it ? Thanx!

**Comment by Allegiance-Consulting** [comment]
Hi,

I have just cloned a fresh copy, did a dotnet restore, built it and then ran it, and it's working.

Can you maybe indicate on which URL your browser is pointing. As it might not be including the correct base href.

It should be something like https://localhost:44383/blazor-highcharts/

![image](https://user-images.githubusercontent.com/60039385/88386464-b7cfab80-cdb0-11ea-892a-929b988c0de1.png)

**Comment by win32nipuh** [comment]
The VS 2019 runs it on 
```
Microsoft.Hosting.Lifetime: Information: Now listening on: https://localhost:5001
Microsoft.Hosting.Lifetime: Information: Now listening on: http://localhost:5000

```

May be it is because settings. 
I try to run the Allegiance.Blazor.Highcharts.ClientSide as a standalone application in VS debugger.

**Comment by Allegiance-Consulting** [comment]
I think there is were the issue is. Can you try running it through IIS express. I think your project is currently trying to use dotnet.exe to run the application. We will investigate to get it to work with both IIS express and dotnet.exe

You can change the runner like this:
![image](https://user-images.githubusercontent.com/60039385/88389591-0d0ebb80-cdb7-11ea-99a8-4b107aad6d74.png)

**Comment by win32nipuh** [comment]
Yes, I will try, but note: your blazor-nouislider works fine when I run it from VS.

**Comment by Allegiance-Consulting** [comment]
You can just change <base href="/blazor-highcharts/" /> to <base href="/" /> build, run and hard refresh Chrome.

**Comment by win32nipuh** [comment]
Btw, what is the Highcharts license? Can I usee it free in my project?
Imagine: I use your wrapper in my project. Your license is MIT, but by fact it uses Highcharts. 
I cannot decide to use or not to use Highcharts because of license.
