### ISSUE TITLE
I cannot find any 3D Pie or 3D Chart in the demo

### ISSUE THREAD

**Issue by win32nipuh** [Allegiance-Consulting/blazor-highcharts#23]
When I run your demo I see 2D Pie but do not see 3D Pie. How to display the 3D?

**Comment by Allegiance-Consulting** [comment]
Hi,

We have not yet ported the 3D version, but you are more than welcome to contribute.

**Comment by win32nipuh** [comment]
I see, thanx. It is what I am searching ;-)

**Comment by win32nipuh** [comment]
What is interesting: their .NET examples 
[](https://dotnet.highcharts.com/Highcharts/Demo/Gallery?demo=PieGradient&theme=default)

shows 2D Pie and Charts only, but no 3D

**Comment by Allegiance-Consulting** [comment]
Please check the latest master. I have added the 3D pie chart.

**Comment by win32nipuh** [comment]
Its great!!! thank you. it works

Another question I have already asked: the license.
Yours is MIT, its ok. But can I use Highcharts  in my projects free or need to buy?

**Comment by Allegiance-Consulting** [comment]
Hi, I believe if your project is non-commercial, you can use Highcharts for free, but otherwise you have to purchase a licence from them. https://shop.highsoft.com/
